export class DealHeaderModel{
    TITLE: string;
    NAME: string;
    TYPE_ID: string;
    STAGE_ID: string;
    PROBABILITY: string;
    OPPORTUNITY: number;
    CURRENCY_ID: string;
    IS_MANUAL_OPPORTUNITY: string = 'N';
    TAX_VALUE: string;
    LEAD_ID: string;
    COMPANY_ID: string;
    CONTACT_ID: string;
    QUOTE_ID: string;
    BEGINDATE: Date = new Date();
    CLOSEDATE: Date= new Date();
    ASSIGNED_BY_ID: string = '1';
    CREATED_BY_ID: string = '1';
    MODIFY_BY_ID: string = '1';
    DATE_CREATE: Date = new Date();
    DATE_MODIFY: Date = new Date();
    OPENED: string = 'Y';
    CLOSED: string = 'N';
    COMMENTS: string;
    ADDITIONAL_INFO: string;
    LOCATION_ID: string;
    CATEGORY_ID: string = '0';
    STAGE_SEMANTIC_ID: string = 'P';
    IS_NEW: string = 'Y';
    IS_RECURRING: string = 'N';
    IS_RETURN_CUSTOMER: string = 'N';
    IS_REPEATED_APPROACH: string = 'N';
    SOURCE_ID: string = '';
    SOURCE_DESCRIPTION: string;
    ORIGINATOR_ID: string;
    ORIGIN_ID: string;
    MOVED_BY_ID: string = '1';
    MOVED_TIME: Date = new Date();
    LAST_ACTIVITY_TIME: Date = new Date();
    UTM_SOURCE: string;
    UTM_MEDIUM: string;
    UTM_CAMPAIGN: string;
    UTM_CONTENT: string;
    UTM_TERM: string;
    LAST_COMMUNICATION_TIME: Date;
    LAST_ACTIVITY_BY: string = '1';
    UF_CRM_1748348209: boolean = false;
    UF_CRM_65AA26E3A3DF8: boolean = false;
    UF_CRM_65AA26E3CC6DE: boolean = false;
    UF_CRM_65AA26E3D585A: boolean = false;
    UF_CRM_65AA26E3DCABD: boolean = false;
    UF_CRM_65AA26E3E4B30: boolean = false;
    UF_CRM_1714624809894: boolean = false;
    UF_CRM_1722574900: boolean = false;
    UF_CRM_1733396738704: boolean = false;
    UF_CRM_68807FD646716: boolean = false;
    OWNER_TYPE: string;
    WAREHOUSE_ID:string;
}